# Note: You can use any Debian/Ubuntu based image you want.
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends python3 python3-pip python3-venv

# WORKDIR /tojo-setup
# COPY requirements.txt .
# RUN python3 -m venv venv
# RUN ./venv/bin/pip install -r requirements.txt
# COPY . .
