[project]
name = "autogen-test"
version = "0.1.0"
description = "Autogen playground for my Agent development"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.7.5",
    "autogen-core>=0.7.5",
    "autogen-ext[ollama,openai]>=0.7.5",
    "dotenv>=0.9.9",
    "ipython>=9.6.0",
    "pandas>=2.3.3",
    "pydantic>=2.11.10",
    "rich>=14.2.0",
    "composio>=0.8.0",
]
