"""initial_schema

Revision ID: 5b2aaeb07965
Revises: 
Create Date: 2026-03-27 00:38:33.428244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2aaeb07965'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('batch_run_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_table('gmail_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('label_patterns',
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_value', sa.String(length=500), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('pattern_weight', sa.Float(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.Column('times_corrected', sa.Integer(), nullable=True),
    sa.Column('is_user_defined', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.String(length=50), nullable=True),
    sa.Column('last_applied_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('pattern_id')
    )
    op.create_index(op.f('ix_label_patterns_user_id'), 'label_patterns', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_label_patterns_user_id'), table_name='label_patterns')
    op.drop_table('label_patterns')
    op.drop_table('gmail_tokens')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_table('classification_sessions')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
